### PR TITLE
Cleanup the image and Dockerfile

### PR DESCRIPTION
**Pull request by williamdes**

### CODE REVIEW

**Comment by williamdes** [comment]
I used [dive](https://github.com/wagoodman/dive) to check what is installed. It's way better but could even be better by removing some python stuff that get's installed.

**Comment by williamdes** [comment]
@crocodile2u could you also update the repository about section ?

**Comment by crocodile2u** [comment]
Hey, thanks for taking care of this! Let me take a quick look, and I'll probably merge it and update dockerhub. Also, a new Mariadb version was released recently, I'll probably make another update based on a fresh base image

**Comment by crocodile2u** [comment]
Done. Thank you, pal. https://hub.docker.com/repository/docker/crocodile2u/mariadb-rocks/general. Latest now points to 10.11 and I added also the 10.11 tag

**Comment by williamdes** [comment]
Awesome!
We could make this image multi arch?
I can build a GitHub workflow for that, you just have to create two GitHub secrets
What do you think?

**Comment by crocodile2u** [comment]
Absolutely, mate. I can also make you a maintainer, cuz I myself don't even use Mariadb or MyRocks these days. I just looked at the repo, and it's been 6 years since start, I switched a few jobs and projects etc ;-)

**Comment by williamdes** [comment]
> Absolutely, mate. I can also make you a maintainer, cuz I myself don't even use Mariadb or MyRocks these days. I just looked at the repo, and it's been 6 years since start, I switched a few jobs and projects etc ;-)

Sure!
You can even transfer the repo to @code-lts where you will have rights on it and I will take care of the repo
And we could continue to upload to the same docker hub account for others users to benefit from that

Else having rights on this repository is perfect too

As you wish!

**Comment by crocodile2u** [comment]
Yup, let's arrange the transfer. Some time around noon (CET) today. I haven't done this ever, but I don't think it's gonna be hard.

**Comment by williamdes** [comment]
> Yup, let's arrange the transfer. Some time around noon (CET) today. I haven't done this ever, but I don't think it's gonna be hard.

I acceptee the invitation and was telling myself it's maybe more @sudo-bot that would make a good host as its mostly docker stuff. As you prefer
So go to the repository settings, and you will find a big transfert button. that's mostly it :)
that will transfer the repository to the organization you choose
Could you invite me on Docker hub to the repository too?
I am not sure that it's possible with the free grade 🤔

**Pull request merged**
